#!/bin/sh

# Regex to validate the commit message
COMMIT_REGEX='^([A-Z].{0,49})\n\n(.{0,72}(\n.{0,72})*)\n\n(ABC-\d{1,4})$'
ERROR_MSG="Aborting commit. Your commit message does not follow the required format. It should end with a ticket number like ABC-1234.\nTo bypass this check, use 'git commit --no-verify'."

if ! grep -qE "$COMMIT_REGEX" "$1"; then
    echo "$ERROR_MSG" >&2
    exit 1
fi
